extract_research_papers_task:
  description: >
    Search for and analyze research papers related to the trend: {trend_title}.
    Description: {trend_description}
    Focus on papers published in the last 3-6 months.
    Look for papers that represent significant advancements or novel approaches.
  expected_output: >
    A list of 3-5 most relevant research papers about this trend, including:
    - Paper title
    - Authors
    - Publication date
    - Brief summary of key findings and contributions
    - Link to the paper
  agent: research_paper_agent

extract_news_articles_task:
  description: >
    Search for news articles about the trend: {trend_title}.
    Description: {trend_description}
    Focus on articles from reputable technology publications in the last week.
    Prioritize in-depth analysis articles over simple news announcements.
  expected_output: >
    A list of 3-5 most informative news articles about this trend, including:
    - Article title
    - Publication name
    - Publication date
    - Brief summary of key points
    - Link to the article
  agent: news_article_agent

extract_social_media_posts_task:
  description: >
    Search for significant social media discussions about the trend: {trend_title}.
    Description: {trend_description}
    Focus on posts from AI researchers, industry leaders, and influential technologists.
    Look for threads that provide unique insights or generate substantial discussion.
  expected_output: >
    A list of 3-5 most insightful social media posts or threads about this trend, including:
    - Author name and credentials
    - Platform (Twitter/X, LinkedIn, etc.)
    - Post date
    - Brief summary of the key points
    - Link to the post/thread
  agent: social_media_agent

extract_github_projects_task:
  description: >
    Search for GitHub projects related to the trend: {trend_title}.
    Description: {trend_description}
    Focus on repositories with active development and good documentation.
    Look for projects that implement or build upon the trend in practical ways.
  expected_output: >
    A list of 3-5 most relevant GitHub projects related to this trend, including:
    - Repository name
    - Creator/organization
    - Brief description of the project
    - Key features or innovations
    - Stars count and last update date
    - Link to the repository
  agent: github_agent

analyze_extracted_data_task:
  description: >
    Analyze all the collected data about the trend: {trend_title}.
    Synthesize insights from research papers, news articles, social media posts, and GitHub projects.
    Identify patterns, contradictions, and connections across different data sources.
  expected_output: >
    A comprehensive analysis of the trend that includes:
    - A unique identifier for the trend
    - Consolidated list of research papers
    - Consolidated list of news articles
    - Consolidated list of social media posts
    - Consolidated list of GitHub projects
    - An analytical summary that highlights the most important aspects of this trend
      based on all collected data
  agent: data_analyst_agent 