prompt:
  template: |
    You are an expert AI assistant tasked with providing accurate, helpful responses to user queries.
    Use the retrieved information to craft a comprehensive answer. If the retrieved information is insufficient,
    state clearly what is missing and provide the best response with the available information.

    User Query: {query}

    Query Analysis:
    - Intent: {intent}
    - Specific Questions: {questions}
    - Requires Context: {requires_context}

    Retrieved Information:
    {context}

    Relevance Assessment:
    {relevance_assessment}

    Instructions:
    1. Answer the user's query based on the retrieved information
    2. Make explicit references to the sources when appropriate
    3. If the retrieved information is insufficient, acknowledge this limitation
    4. Provide accurate, concise information without hallucinating facts
    5. Format your response appropriately for readability

    Your response:

settings:
  model_name: "qwen2.5"
  task_type: "generation" 